/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Boolean_10: THREE.Mesh
    Boolean_9: THREE.Mesh
    Boolean_2004: THREE.Mesh
    Boolean_3: THREE.Mesh
    Boolean_4: THREE.Mesh
    Boolean_6: THREE.Mesh
    Boolean_7: THREE.Mesh
    Boolean_8: THREE.Mesh
    Boolean009: THREE.Mesh
    Boolean008: THREE.Mesh
    Rectangle_14: THREE.Mesh
    Rectangle_17: THREE.Mesh
    Rectangle_18: THREE.Mesh
    Rectangle_22: THREE.Mesh
    Rectangle_24: THREE.Mesh
    Rectangle_25: THREE.Mesh
    Rectangle_27: THREE.Mesh
    Rectangle_28: THREE.Mesh
    Rectangle_23: THREE.Mesh
    Rectangle_29: THREE.Mesh
    Rectangle_2004: THREE.Mesh
    Rectangle_30: THREE.Mesh
    Rectangle_31: THREE.Mesh
    Rectangle_34: THREE.Mesh
    Rectangle_35: THREE.Mesh
    Boolean006: THREE.Mesh
    Boolean002: THREE.Mesh
    Rectangle_2: THREE.Mesh
    Boolean005: THREE.Mesh
    Rectangle_2003: THREE.Mesh
    Boolean003: THREE.Mesh
    Rectangle_2001: THREE.Mesh
    Boolean004: THREE.Mesh
    Rectangle_2002: THREE.Mesh
    Boolean: THREE.Mesh
    Boolean_2001: THREE.Mesh
    Rectangle001: THREE.Mesh
    Boolean_2: THREE.Mesh
    Rectangle: THREE.Mesh
    Boolean007: THREE.Mesh
    Boolean_2003: THREE.Mesh
    Rectangle002: THREE.Mesh
    Boolean001: THREE.Mesh
    Boolean_2002: THREE.Mesh
    Rectangle_3: THREE.Mesh
    vidro: THREE.Mesh
    Arduino001_0: THREE.Mesh
    Plane003_0: THREE.Mesh
    Arduino002_0: THREE.Mesh
    Plane001_0: THREE.Mesh
    Arduino003_0: THREE.Mesh
    Arduino004_0: THREE.Mesh
    Arduino005_0: THREE.Mesh
    Arduino005_1: THREE.Mesh
    Arduino005_2: THREE.Mesh
    Arduino006_0: THREE.Mesh
    Arduino006_1: THREE.Mesh
    Arduino006_2: THREE.Mesh
    Arduino006_3: THREE.Mesh
    Arduino007_0: THREE.Mesh
    Arduino008_0: THREE.Mesh
    Arduino008_1: THREE.Mesh
    Arduino008_2: THREE.Mesh
    Arduino008_3: THREE.Mesh
    Arduino008_4: THREE.Mesh
    Arduino009_0: THREE.Mesh
    Arduino009_1: THREE.Mesh
    Arduino010_0: THREE.Mesh
    Arduino010_1: THREE.Mesh
    Arduino010_2: THREE.Mesh
    Arduino011_0: THREE.Mesh
    Text: THREE.Mesh
    caixaB: THREE.Mesh
    caixaC: THREE.Mesh
    defaultMaterial: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    vovimento_2: THREE.Mesh
  }
  materials: {
    ["cor parede"]: THREE.MeshStandardMaterial
    ["Materiais.001"]: THREE.MeshStandardMaterial
    ["Materiais.003"]: THREE.MeshStandardMaterial
    ["Materiais.002"]: THREE.MeshStandardMaterial
    Materiais: THREE.MeshStandardMaterial
    janela: THREE.MeshStandardMaterial
  }
}

export function CasaModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("http://localhost:3000/models/animationsCasa.glb") as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group<THREE.Object3DEventMap>>(null);
  window.addEventListener("click", () => {
    console.log(groupRef);
    
  });
  return (
    <group ref={groupRef} {...props} dispose={null} scale={0.2}>
      <group position={[-0.041, -9.359, 2.901]} scale={0.316}>
        <group position={[-0.745, -4.065, 3.239]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boolean_10.geometry}
            material={materials["cor parede"]}
            position={[-931.049, -13.311, -189.604]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boolean_9.geometry}
            material={materials["Materiais.001"]}
            position={[2.117, 210.913, -2.041]}
          />
          <group position={[7.819, -12.708, 0.212]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_2004.geometry}
              material={materials["cor parede"]}
              position={[93.772, -98.22, -388.29]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_3.geometry}
              material={materials["cor parede"]}
              position={[-380.298, -98.22, -340.483]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_4.geometry}
              material={materials["cor parede"]}
              position={[-768.716, -98.22, -377.812]}
              scale={[0.976, 1, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_6.geometry}
              material={materials["cor parede"]}
              position={[354.749, 94.688, 7.221]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_7.geometry}
              material={materials["cor parede"]}
              position={[648.739, 96.344, -301.995]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean_8.geometry}
              material={materials["cor parede"]}
              position={[-814.674, 0.398, 195.224]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean009.geometry}
              material={materials["cor parede"]}
              position={[354.749, -98.215, 7.221]}
            />
            <group position={[882.767, -98.58, 389.721]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Boolean008.geometry}
                material={materials["Materiais.003"]}
                position={[-0.365, 390.7, 57.428]}
              />
            </group>
            <group position={[123.917, -0.531, 62.502]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_14.geometry}
                material={materials["cor parede"]}
                position={[-61.791, -195.301, 354.435]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.254}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_17.geometry}
                material={materials["cor parede"]}
                position={[-720.151, -195.296, -411.979]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.254}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_18.geometry}
                material={materials["cor parede"]}
                position={[-280.33, -195.296, -318.477]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.254}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_22.geometry}
                material={materials["cor parede"]}
                position={[-993.458, -195.301, -80.955]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[3.406, 3.254, 3.254]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_24.geometry}
                material={materials["cor parede"]}
                position={[819.186, 1.363, -7.446]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.25}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_25.geometry}
                material={materials["cor parede"]}
                position={[-61.791, -3.357, 354.435]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={3.254}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_27.geometry}
                material={materials["cor parede"]}
                position={[810.644, 1.363, -398.945]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[5.02, 0.82, 3.25]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_28.geometry}
                material={materials["cor parede"]}
                position={[522.2, 2.363, -473.117]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={[5.02, 0.82, 3.25]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_23.geometry}
              material={materials["Materiais.002"]}
              position={[650.71, 1.109, -3.628]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_29.geometry}
              material={materials.Materiais}
              position={[-822.103, 3.663, 206.75]}
              rotation={[0, -1.571, 0]}
              scale={[0.65, 1, 1]}
            />
          </group>
          <group position={[-93.165, -227.403, -189.285]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2004.geometry}
              material={materials["Materiais.002"]}
              position={[91.304, 17.696, 192.903]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.709, 0.498, 1]}
            />
          </group>
          <group position={[-874.921, 29.843, 204.543]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_30.geometry}
              material={materials["cor parede"]}
              position={[-56.553, -34.443, -1.646]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[3.25, 0.717, 3.25]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_31.geometry}
              material={materials["cor parede"]}
              position={[0.023, -34.443, 210.309]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[3.25, 0.717, 3.25]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_34.geometry}
            material={materials.Materiais}
            position={[0.806, 207.712, -7.988]}
            rotation={[-1.509, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_35.geometry}
            material={materials.janela}
            position={[-899.691, -3.552, -200.132]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
        <group position={[-551.911, -89.665, -386.735]}>
          <group position={[182.518, 4, 50.841]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean006.geometry}
              material={materials["Materiais.001"]}
              position={[0, 0, -1.943]}
            />
            <group position={[-88.492, 0.392, 5.923]} scale={[1.013, 1, 1]}>
              <group position={[0, 0, -2.407]} scale={[1, 1, 0.388]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Boolean002.geometry}
                  material={nodes.Boolean002.material}
                  position={[0, 0, -10.146]}
                  scale={[0.239, 0.947, 0.776]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2.geometry}
                  material={materials.janela}
                  position={[0.026, 1.572, -11.222]}
                  rotation={[-3.136, 0, 0]}
                  scale={[0.239, 0.914, 0.07]}
                />
              </group>
              <group position={[174.42, 0, -4.687]} scale={[1, 1, 0.388]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Boolean005.geometry}
                  material={nodes.Boolean005.material}
                  position={[0, 0, -10.146]}
                  scale={[0.239, 0.947, 0.776]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2003.geometry}
                  material={materials.janela}
                  position={[0.026, 1.572, -11.222]}
                  rotation={[-3.136, 0, 0]}
                  scale={[0.239, 0.914, 0.07]}
                />
              </group>
              <group position={[-0.17, 0, -1.981]} scale={[1, 1, 0.388]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Boolean003.geometry}
                  material={nodes.Boolean003.material}
                  position={[0, 0, -10.146]}
                  scale={[0.239, 0.947, 0.776]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2001.geometry}
                  material={materials.janela}
                  position={[0.026, 1.572, -11.222]}
                  rotation={[-3.136, 0, 0]}
                  scale={[0.239, 0.914, 0.07]}
                />
              </group>
              <group position={[175.08, 0, -1.981]} scale={[1, 1, 0.388]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Boolean004.geometry}
                  material={nodes.Boolean004.material}
                  position={[0, 0, -10.146]}
                  scale={[0.239, 0.947, 0.776]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2002.geometry}
                  material={materials.janela}
                  position={[0.026, 1.572, -11.222]}
                  rotation={[-3.136, 0, 0]}
                  scale={[0.239, 0.914, 0.07]}
                />
              </group>
            </group>
          </group>
          <group position={[-254.401, -3.455, 667.469]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean.geometry}
              material={nodes.Boolean.material}
              position={[0.868, 0, 0]}
            />
            <group position={[-2.32, 0, -47.575]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Boolean_2001.geometry}
                material={nodes.Boolean_2001.material}
                position={[0.279, 0, 0]}
                scale={[0.322, 0.893, 0.477]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle001.geometry}
                material={materials.janela}
                position={[0.616, 0.312, 0.207]}
                rotation={[0, -1.571, 0]}
                scale={[0.96, 0.896, 0.747]}
              />
            </group>
            <group position={[0.964, 0, -47.575]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Boolean_2.geometry}
                material={nodes.Boolean_2.material}
                position={[0.279, 0, 0]}
                scale={[0.322, 0.893, 0.477]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle.geometry}
                material={nodes.Rectangle.material}
                position={[0.616, 0.312, 0.207]}
                rotation={[0, -1.571, 0]}
                scale={[0.96, 0.896, 0.747]}
              />
            </group>
          </group>
          <group position={[-208.125, -4, -27.105]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean007.geometry}
              material={materials["Materiais.001"]}
              position={[0.765, -0.005, 37.111]}
            />
            <group position={[-1.39, 16.957, 0.39]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Boolean_2003.geometry}
                material={nodes.Boolean_2003.material}
                position={[0.727, 0.394, -0.281]}
                rotation={[0.96, 0, 0]}
                scale={[0.95, 0.95, 0.503]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle002.geometry}
                material={materials.janela}
                position={[-0.413, 0.957, -0.927]}
                rotation={[0.966, 0, -Math.PI]}
                scale={[0.963, 0.954, 0.133]}
              />
            </group>
          </group>
          <group position={[501.303, 52.363, -1.234]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Boolean001.geometry}
              material={materials["Materiais.001"]}
              position={[-0.236, 0.325, 0]}
            />
            <group position={[-29.34, 0.325, -42.61]} rotation={[0, 1.237, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Boolean_2002.geometry}
                material={nodes.Boolean_2002.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rectangle_3.geometry}
                material={materials.janela}
                position={[0, 0, 0.967]}
                rotation={[-Math.PI, 0, 0]}
                scale={[0.92, 0.894, 0.021]}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vidro.geometry}
            material={materials.janela}
            position={[798.299, 123.551, 1.539]}
            rotation={[-Math.PI, 0, 0]}
            scale={[1, 1, 0.075]}
          />
        </group>
        <group
          position={[-670.847, -57.629, -373.713]}
          rotation={[-2.453, -1.56, -2.412]}
          scale={0.098}>
          <group
            position={[84.293, 77.822, 42.889]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={42.585}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.325}>
              <group position={[-1.55, -1.872, 0]} rotation={[0, 0, Math.PI / 2]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino001_0.geometry}
                  material={nodes.Arduino001_0.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane003_0.geometry}
                  material={nodes.Plane003_0.material}
                />
              </group>
              <group position={[0, 0, -0.044]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino006_0.geometry}
                  material={nodes.Arduino006_0.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino006_1.geometry}
                  material={nodes.Arduino006_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino006_2.geometry}
                  material={nodes.Arduino006_2.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino006_3.geometry}
                  material={nodes.Arduino006_3.material}
                />
              </group>
              <group position={[0.473, -0.235, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino008_0.geometry}
                  material={nodes.Arduino008_0.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino008_1.geometry}
                  material={nodes.Arduino008_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino008_2.geometry}
                  material={nodes.Arduino008_2.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino008_3.geometry}
                  material={nodes.Arduino008_3.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino008_4.geometry}
                  material={nodes.Arduino008_4.material}
                />
              </group>
              <group position={[0.473, -0.235, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino009_0.geometry}
                  material={nodes.Arduino009_0.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino009_1.geometry}
                  material={nodes.Arduino009_1.material}
                />
              </group>
              <group position={[1.418, -1.367, 0.39]} scale={[1.854, 0.347, 1.288]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino010_0.geometry}
                  material={nodes.Arduino010_0.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino010_1.geometry}
                  material={nodes.Arduino010_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Arduino010_2.geometry}
                  material={nodes.Arduino010_2.material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino002_0.geometry}
                material={nodes.Arduino002_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_0.geometry}
                material={nodes.Plane001_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino003_0.geometry}
                material={nodes.Arduino003_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino004_0.geometry}
                material={nodes.Arduino004_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino005_0.geometry}
                material={nodes.Arduino005_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino005_1.geometry}
                material={nodes.Arduino005_1.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino005_2.geometry}
                material={nodes.Arduino005_2.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino007_0.geometry}
                material={nodes.Arduino007_0.material}
                position={[0.035, 0.018, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Arduino011_0.geometry}
                material={nodes.Arduino011_0.material}
                position={[0, 0, -0.045]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Text.geometry}
              material={nodes.Text.material}
              position={[0.449, 0.009, -0.43]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.012, 0.012, 0.006]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.caixaB.geometry}
            material={nodes.caixaB.material}
            position={[83.444, -87.064, 0.001]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.caixaC.geometry}
            material={nodes.caixaC.material}
            position={[83.444, 95.476, 0]}
            rotation={[-Math.PI, 0, 0]}
            scale={[1, 0.81, 1]}
          />
          <group position={[99.817, -56.465, 22.611]} scale={43.959}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={nodes.defaultMaterial.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={nodes.defaultMaterial_2.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={nodes.defaultMaterial_1.material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vovimento_2.geometry}
            material={nodes.vovimento_2.material}
            position={[41.99, -110.221, -2]}
            rotation={[0, 0, 0.46]}
            scale={31.491}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("http://localhost:3000/models/animationsCasa.glb");