/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Corpo3: THREE.Mesh
    Corpo4: THREE.Mesh
    Corpo26: THREE.Mesh
  }
  materials: {
    Materiais: THREE.MeshStandardMaterial
    ["Materiais.001"]: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/controler1.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} scale={1/9}  >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Corpo3.geometry}
        material={materials.Materiais}
        position={[0, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={8.53}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Corpo4.geometry}
        material={materials.Materiais}
        position={[0.209, 9.279, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={8.53}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Corpo26.geometry}
        material={materials["Materiais.001"]}
        position={[-2.184, 11, -1.5]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={8.53}
      />
    </group>
  );
}

useGLTF.preload("models/controler1.glb");