/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/grub.glb 
Author: ARKON MAREK (https://sketchfab.com/ARKON-83)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hollow-knight-trapped-grub-1723f50da7fe4a0097854b56d4fdf5a3
Title: -Hollow Knight- Trapped Grub
*/

import { useGraph } from "@react-three/fiber";
import { useGLTF,  } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useMemo } from "react";

export default function Grub(props) {
  const model = useGLTF("models/grub.glb");
  const clone = useMemo(() => SkeletonUtils.clone(model.scene), [model.scene]);
  const { nodes, materials } = useGraph(clone);

  return (
    <group {...props} dispose={null} >
      <group scale={0.01}>
        <group
          position={[0, -200, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_20.geometry}
            material={materials.Grub}
            skeleton={nodes.Object_20.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_22.geometry}
            material={materials.Blacklines}
            skeleton={nodes.Object_22.skeleton}
          />
        </group>
        <group
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[468.796, 468.796, 379.893]}
        >
          <mesh

            geometry={nodes.Jar001_Glass_0.geometry}
            material={materials.Glass}
          />
          <mesh
            geometry={nodes.Cube002_Pot_0.geometry}
            material={materials.material}
            position={[0, 0, 0.976]}
          />
          <mesh
            geometry={nodes.Plane002_Pot_0.geometry}
            material={materials.material}
            position={[0, 0, 1.201]}
            scale={[0.056, 0.056, 0.07]}
          />
        </group>
        <group
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[490.045, 490.045, 397.112]}
        >
          <mesh
            geometry={nodes.Jar_Linework001_Blacklines_0.geometry}
            material={materials.Blacklines}
          />
          <mesh
            geometry={nodes.Cube004_Blacklines_0.geometry}
            material={materials.Blacklines}
            position={[0, 0, 0.934]}
            scale={0.954}
          />
          <mesh
            geometry={nodes.Plane003_Blacklines_0.geometry}
            material={materials.Blacklines}
            position={[0, 0, 1.149]}
            scale={[0.054, 0.054, 0.067]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/grub.glb");
