/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { JSX, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Corpo3: THREE.Mesh
    Corpo6: THREE.Mesh
    defaultMaterial: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    Corpo4: THREE.Mesh
    Corpo5: THREE.Mesh
    Cube025_ESP_SIDE_0: THREE.Mesh
    Cube025_ESP_0: THREE.Mesh
  }
  materials: {
    ["Material.023"]: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ESP_SIDE: THREE.MeshStandardMaterial
    ["latao.005"]: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

export function OpenCase(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/open_case.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[4963.466, 2766.373, 5923.518]}>
          <group position={[0, -114.956, -1158.44]}>
            <group
              position={[0, -1149.862, -511.048]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={148.802}>
              <group position={[0, -14.073, 8.5]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Corpo3.geometry}
                  material={materials["Material.023"]}
                  position={[0, 1.575, 0.06]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Corpo6.geometry}
                  material={materials.Material}
                  position={[-0.129, -2.676, -3.243]}
                  rotation={[0, -1.571, 0]}
                />
                <group
                  position={[0.422, 2.649, -4.74]}
                  rotation={[-1.571, 1.56, 1.571]}
                  scale={1.946}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.defaultMaterial.geometry}
                    material={nodes.defaultMaterial.material}
                    position={[0, -0.008, 0.074]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.defaultMaterial_2.geometry}
                    material={materials.ESP_SIDE}
                    position={[0, -0.148, 0.077]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.defaultMaterial_1.geometry}
                    material={nodes.defaultMaterial_1.material}
                    position={[0.022, -0.065, -0.382]}
                  />
                </group>
              </group>
              <group position={[0, -6.545, 8.5]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Corpo4.geometry}
                  material={materials["Material.023"]}
                  position={[-9.355, 0.812, 0]}
                  rotation={[0, 0, 2.083]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Corpo5.geometry}
                  material={materials["latao.005"]}
                  position={[-10.711, 0.057, -3.5]}
                  rotation={[0, 0, -1.107]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={1.066}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_ESP_SIDE_0.geometry}
            material={materials.ESP_SIDE}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube025_ESP_0.geometry}
            material={materials.material}
            position={[3589.461, -4708.345, 2248.477]}
            rotation={[-Math.PI / 2, 0.967, -Math.PI / 2]}
            scale={365.381}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/caixaMot.glb");