/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/HORNET.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export function Hornet(props, ref) {

  const { scene, animations } = useGLTF("models/HORNET.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, ref);
  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
      position={[0,-.85,2]}
      // rotation={[0,1,0]}
      // onPointerMove={(e) => handleAnimationSeekCursor(e)}
      
      // onPointerLeave={handleAnimationexit}
    >
      <group name="Scene">
        <group name="HORNET_RIG">
          <primitive object={nodes.PELVIS} />
          <primitive object={nodes.NEEDLE_BONE} />
          <skinnedMesh
            name="DRESS001"
            geometry={nodes.DRESS001.geometry}
            material={materials.DRESS}
            skeleton={nodes.DRESS001.skeleton}
          />
          <group name="HORNET_BODY001">
            <skinnedMesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.HEAD}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              name="Cube001_1"
              geometry={nodes.Cube001_1.geometry}
              material={materials.BODY}
              skeleton={nodes.Cube001_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="NEEDLE001"
            geometry={nodes.NEEDLE001.geometry}
            material={materials.NEEDLE}
            skeleton={nodes.NEEDLE001.skeleton}
          />
        </group>
        <mesh
          name="SILK_LINE"
          geometry={nodes.SILK_LINE.geometry}
          material={materials["SILK LINE MATERIAL"]}
        />
        <mesh
          name="SHADOW"
          geometry={nodes.SHADOW.geometry}
          material={materials.shadow}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/HORNET.glb");
