import type { Metadata } from "next";
import { Chakra_Petch, Major_Mono_Display } from "next/font/google";
import "./globals.css";
import Transition from "@/components/transition";
import { Mouse } from "@/components/Mouse";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  subsets: ["latin"],
  weight: ["300", "400"]
});

const majorMonoDisplay = Major_Mono_Display({
  variable: "--font-major-mono-display",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chakraPetch.variable} ${majorMonoDisplay.variable} antialiased **:cursor-none`}
      >
        <Mouse/>
        <Transition>{children}</Transition>
      </body>
    </html>
  );
}
