/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata } from "next";
import { Chakra_Petch, Major_Mono_Display } from "next/font/google";
import { GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";


import Transition from "@/components/transition";
import { Mouse } from "@/components/Mouse";
import BuyCardContainer from "@/components/buy-card";
import Navbar from "@/components/navbar/";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  subsets: ["latin"],
  weight: ["300", "400"]
});

const majorMonoDisplay = Major_Mono_Display({
  variable: "--font-major-mono-display",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Risk Of Rain",
  description: "Generated by create next app"
};

const googleTagId = process.env.NEXT_PUBLIC_MEASUREMENT_ID ?? "";

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-scroll-behavior="smooth">
      <GoogleTagManager gtmId={googleTagId} />
      <body
        data-scroll-behavior="smooth"
        className={`${chakraPetch.variable} ${majorMonoDisplay.variable} antialiased **:cursor-none scroll-smooth 
        [&::-webkit-scrollbar]:w-1
  [&::-webkit-scrollbar-track]:bg-dark-10
  [&::-webkit-scrollbar-track]:bordersecondary-01
  [&::-webkit-scrollbar-track]:boder
  [&::-webkit-scrollbar-thumb]:bg-secondary-01
  [&::-webkit-scrollbar-thumb]:border-secondary-01
  [&::-webkit-scrollbar-thumb]:border
  `}
      >

        <Mouse />
      <script type="text/javascript" charSet="UTF-8" src="//cdn.cookie-script.com/s/b307311af8258c05bc4f7458c080e9c0.js"></script>
        {/* <Enter> */}
        <Transition>
          <BuyCardContainer />
          <Navbar />
          {children}
        </Transition>
        {/* </Enter> */}
      </body>
    </html>
  );
}
