import type { Metadata } from "next";
import { Chakra_Petch, Major_Mono_Display } from "next/font/google";
import "./globals.css";

import Transition from "@/components/transition";
import { Mouse } from "@/components/Mouse";
import Enter from "./enterOnce";
import BuyCardContainer from "@/components/buy-card";
import Navbar from "@/components/navbar/";

const chakraPetch = Chakra_Petch({
  variable: "--font-chakra-petch",
  subsets: ["latin"],
  weight: ["300", "400"]
});

const majorMonoDisplay = Major_Mono_Display({
  variable: "--font-major-mono-display",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Risk Of Rain",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
      data-scroll-behavior="smooth"
        className={`${chakraPetch.variable} ${majorMonoDisplay.variable} antialiased **:cursor-none scroll-smooth`}
      >
        <Mouse />
        {/* <Enter> */}
        <Transition>
          <BuyCardContainer />
          <Navbar />
          {children}
        </Transition>
        {/* </Enter> */}
      </body>
    </html>
  );
}
